eureka:
  client:
    shouldFetchRegistry: false
  instance:
    port: 7000
mysql:
  client:
    database: steeltoe3
    username: root
    password: steeltoe
postgres:
  client:
    database: steeltoe3
    username: steeltoe
    password: steeltoe